apiVersion: v1
kind: Service
metadata:
  name: config-service
  namespace: tst
  labels:
    app: config-service
    profile: tst  # Add the profile label here
spec:
  selector:
    app: config-service
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30001
  type: NodePort