apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Set the namespace for all resources
namespace: tst

# SecretGenerator to generate the secret from the .env file
secretGenerator:
  - name: kube-pass
    envs:
      - .env

# Optional: Disable name suffix hashing (if you want to keep the name exactly as defined)
generatorOptions:
  disableNameSuffixHash: true
